CREATE DATABASE Customer_behaviour;

USE Customer_behaviour;

SELECT * FROM customer
LIMIT 10;

-- Q1 What is the total revenue generated by male vs female customers?

SELECT gender,SUM(purchase_amount) AS Total_revenue
FROM customer
GROUP BY gender;

-- Q2 Which customer used discount but still spent more than average purchase amount?

SELECT customer_id,purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount> (SELECT AVG(purchase_amount) FROM customer);

-- Q3 Which are the top 5 products with the highest average review rating?

SELECT item_purchased,AVG(review_rating) AS Avergae_product_rating 
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4 Compare average purchase amount between Standard and express shipping?

SELECT shipping_type,AVG(purchase_amount) 
FROM customer
WHERE shipping_type IN ('Standard' , 'Express')
GROUP BY shipping_type
ORDER BY AVG(purchase_amount) DESC;

-- Q5 Do subscribed customers spend more? Compare average spend and total revenue between subscriber and non subscribers

SELECT subscription_status,COUNT(customer_id),SUM(purchase_amount),AVG(purchase_amount)
FROM customer
GROUP BY subscription_status
ORDER BY SUM(purchase_amount),AVG(purchase_amount) DESC;

-- Q6 Which 5 products have the highest percentage of purchases with discount applied?

SELECT item_purchased,
(100*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)) /COUNT(*)AS Percentage
FROM customer
GROUP BY item_purchased
ORDER BY Percentage DESC
LIMIT 5;

-- Q7 Segments customers into New,Returning and loyal based on their total number of previous purchases, and show the count of each segment?

WITH customer_type AS (
SELECT customer_id,item_purchased,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer
)

SELECT customer_segment,COUNT(*) AS "Number of Customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8 What are the top 3 most purchased products within each category?

WITH item_counts AS(
SELECT category,
item_purchased,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category,item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <=3;

-- Q9 Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10 What is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
